version: 2
updates:
- package-ecosystem: npm
  directory: "/invoices_svc"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/expected_date_svc"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/auth_svc"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
